trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: PowershellBuild
    Contents: '*powershellInstall.sh'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'

- task: SSH@0
  displayName: 'Run shell script on remote machine'
  inputs:
    sshEndpoint: Testing
    runOptions: script
    scriptPath: '$(System.DefaultWorkingDirectory)/_$(Build.DefinitionName)/drop/powershellInstall.sh'

#- task: SSH@0
#  displayName: 'Run shell script on remote machine'
#  inputs:
#    sshEndpoint: Testing
#    runOptions: script
#    scriptPath: '$(System.DefaultWorkingDirectory)/_AzureDevOpsRecipes (1)/drop/powershellInstall.sh'
