trigger:
- master

stages:
  - stage: Build
    displayName: Build Stage for SSH script
    jobs:
    - job: Build
      displayName: Build job
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: CopyFiles@2
        displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
        inputs:
          SourceFolder: PowershellBuild
          Contents: '*powershellInstall.sh'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
