apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest
spec:
  selector:
    matchLabels:
      app: nginxtest
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - name: nginxtest
        image: nginx:latest
        ports:
        - containerPort: 80